# Change these first
owner: moechs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Plus Repo
    url: https://repo.plus
  - name: Plus Repo TCP Ping
    url: repo.plus
    port: 443
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.repo.plus
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Uptime monitor and status page**"
  # introMessage: 
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
